package tech.benhack.common

enum class CategoryType {
    NOW_PLAYING_MOVIES,
    POPULAR_MOVIES,
    UPCOMING_MOVIES,
    WATCH_LIST_MOVIES,
    HISTORY_MOVIES,
    // TODO: DELETE FAVORITE_PEOPLE. IT DOES NOT BELONG TO MOVIE CATEGORY
    FAVORITE_PEOPLE
}